#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'

cookbook 'ruby_build',
           :git => 'git://github.com/fnichol/chef-ruby_build.git',  :ref => 'v0.6.2'
cookbook 'rbenv',
           :git => 'https://github.com/fnichol/chef-rbenv',  :ref => '7d9b66f20d6edb786720b22919fd53e698fce12b'
cookbook 'apt', :git => 'https://github.com/opscode-cookbooks/apt'
cookbook 'yum', :git => 'https://github.com/opscode-cookbooks/yum'
cookbook 'mysql', :git => 'https://github.com/opscode-cookbooks/mysql'
cookbook 'apache2', :git => 'https://github.com/opscode-cookbooks/apache2'
cookbook 'passenger_apache2', :git => 'https://github.com/opscode-cookbooks/passenger_apache2'
cookbook 'unicorn'
cookbook 'nginx'
cookbook 'runit'
cookbook 'nodejs'
